if (typeof arr == "undefined" || !(arr instanceof Array)) {
var arr = [];
let val = "commits";
let name = "Commits per Author:";
}
val = "commits";
name = "Commits per Author:";
 let tabNamesCommits = [];
let tabCommits = [];
tabNamesCommits.push("ZAPFACK MESSIANE jasen steve <messianezapfack@gmail.com>");
tabCommits.push("8");
tabNamesCommits.push("Yahya <yahyahamdi240@gmail.com>");
tabCommits.push("5");
tabNamesCommits.push("ELKHCHAI nabil <nabilelkhchaii@gmail.com>");
tabCommits.push("1");
tabNamesCommits.push("MOHUN shuaib <shuaib.2106@gmail.com>");
tabCommits.push("6");
tabNamesCommits.push("seddik <cherif.seddik2002@gmail.com>");
tabCommits.push("14");
tabNamesCommits.push("Xavier Denis <xldenis@gmail.com>");
tabCommits.push("2");
tabNamesCommits.push("HAMDI yahya <hamdiyahya240@gmail.com>");
tabCommits.push("1");
tabNamesCommits.push("jasen <messianezapfack@gmail.com>");
tabCommits.push("11");
tabNamesCommits.push("Amaury Moncorge <amoncorge@t09.script.univ-paris-diderot.fr>");
tabCommits.push("4");
tabNamesCommits.push("MONCORGE amaury <amaury.yvan@gmail.com>");
tabCommits.push("2");
tabNamesCommits.push("SEDDIK mohamed cherif <cherif.seddik2002@gmail.com>");
tabCommits.push("2");
tabNamesCommits.push("Shuaib Mohun <shuaib.2106@gmail.com>");
tabCommits.push("14");
tabNamesCommits.push("Aldric Degorre <adegorre@irif.fr>");
tabCommits.push("12");
tabNamesCommits.push("Colin Gonzalez <colin@nomadic-labs.com>");
tabCommits.push("1");
tabNamesCommits.push("Amaury <amaury.yvan@gmail.com>");
tabCommits.push("4");
tabNamesCommits.push("Shuaib Mohun <smohun@t08.script.univ-paris-diderot.fr>");
tabCommits.push("1");
tabNamesCommits.push("gio <gio@irif.fr>");
tabCommits.push("1");
arr[val] = tabCommits;arr[name] = tabNamesCommits;